name: MyTradeMate
options:
  minimumXcodeGenVersion: 2.38.0

fileGroups:
  - MyTradeMate

targets:
  MyTradeMate:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: MyTradeMate
        excludes:
          - "Tests/**"
          - "Info.plist"
          - "README.md"
          - "**/README.md"
          - "AI/ADXStrategy.swift"
          - "AI/BollingerBandsStrategy.swift"
          - "AI/IchimokuStrategy.swift" 
          - "AI/WilliamsRStrategy.swift"
          - "Core/AppConfig.swift"
          - "Core/BinanceClient.swift"
          - "Core/BinanceExchangeClient.swift"
          - "Core/BinanceModels.swift"
          - "Core/KrakenClient.swift"
          - "Core/KrakenExchangeClient.swift"
          - "Core/KrakenModels.swift"
          - "Core/SignalEngine.swift"
          - "Core/SymbolCatalog.swift"
          - "Core/TradeStore.swift"
          - "Core/WebSocketManager.swift"
          - "Models/Asset.swift"
          - "Models/AppSettings.swift"
          - "Services/BinanceLiveClient.swift"
          - "Services/CandleProvider.swift"
          - "Services/ExchangeClient.swift"
          - "Services/KrakenLiveClient.swift"
          - "Services/MarketDataService.swift"
          - "Services/ModeEngine.swift"
          - "Services/PaperExchangeClient.swift"
          - "Settings/SettingsValidator.swift"
          - "Views/DashboardView.swift"
          - "Views/ExchangeKeysView.swift"
          - "Views/Settings/**"
          - "Views/StrategiesView.swift"
          - "Views/TradeHistoryView.swift"
          - "Views/TradesView.swift"
          - "Scripts/**"
        createIntermediateGroups: true
    resources:
      - path: MyTradeMate/Info.plist
    settings:
      base:
        PRODUCT_NAME: MyTradeMate
        PRODUCT_BUNDLE_IDENTIFIER: com.gmail.mytrademate.app
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: MyTradeMate/Info.plist
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    scheme:
      testTargets:
        - MyTradeMateTests

  MyTradeMateTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MyTradeMate/Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gmail.mytrademate.app.tests
        BUNDLE_LOADER: $(BUILT_PRODUCTS_DIR)/MyTradeMate.app/MyTradeMate
        TEST_HOST: $(BUNDLE_LOADER)

  MyTradeMateWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: MyTradeMateWidget
    settings:
      base:
        PRODUCT_NAME: MyTradeMateWidget
        PRODUCT_BUNDLE_IDENTIFIER: com.gmail.mytrademate.app.widget
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: MyTradeMateWidget/Info.plist
    dependencies:
      - target: MyTradeMate