name: MyTradeMate
options:
  minimumXcodeGenVersion: 2.38.0

fileGroups:
  - MyTradeMate

targets:
  MyTradeMate:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: MyTradeMate
        excludes:
          - "Info.plist"
        createIntermediateGroups: true
    resources:
      - path: MyTradeMate/Info.plist
    settings:
      base:
        PRODUCT_NAME: MyTradeMate
        PRODUCT_BUNDLE_IDENTIFIER: com.gmail.mytrademate.app
        SWIFT_VERSION: 5.0
        INFOPLIST_FILE: MyTradeMate/Info.plist
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    scheme:
      testTargets:
        - MyTradeMateTests

  MyTradeMateTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MyTradeMateTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gmail.mytrademate.app.tests
        BUNDLE_LOADER: $(BUILT_PRODUCTS_DIR)/MyTradeMate.app/MyTradeMate
        TEST_HOST: $(BUNDLE_LOADER)